# Generated by Django 4.2.1 on 2023-05-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usercreate',
        ),
    ]
