# Generated by Django 4.2.1 on 2023-05-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usercreate_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreate',
            old_name='name',
            new_name='realname',
        ),
    ]
