# Generated by Django 4.2.1 on 2023-05-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_usercreate_realname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usercreate',
            new_name='User',
        ),
    ]
